      $SET KEYCOMPRESS "7"
000010     SELECT INVOICE ASSIGN DISK
000020                    LOCK MANUAL
000030                    WITH LOCK ON MULTIPLE RECORDS
000040                    STATUS WS-STATUS
000050                    ACCESS DYNAMIC
000060                    ORGANIZATION INDEXED
000070			  RECORD DOC-RMKEY =
			    DOC-AC DOC-SEVEN DOC-ONE DOC-SEQN
                          ALTERNATE RECORD DOC-AKEY = 
			    DOC-AC DOC-TYPE DOC-SEVEN DOC-ONE DUPLICATES
			  ALTERNATE RECORD DOC-DKEY =
			    DOC-DTE DOC-SEVEN DOC-ONE DOC-SQN DUPLICATES
			  ALTERNATE RECORD DOC-RKEY =
			    DOC-SEVEN DOC-ONE DOC-SQN DUPLICATES.
      $SET NOKEYCOMPRESS
